name: my-first-workflow
#To get the workflow triggeered at every push
on: 
 push:
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    
    steps:
      - name: Running single command in JOB1
        run: echo "Hi this is Hemant's workdlow"
      - name: check1
        run: |
          pwd
          ls -al
          hostname
      - name: Step 2 Checkout
        uses: actions/checkout@v6.1.0

      - name: Step 3 Check
        run: |
          pwd
          ls -al
          hostname
