name: my-first-workflow
#To get the workflow triggeered at every push
on: 
 push:
   branches: 
    - main

     
env:
  ENV_TYPE: demo
  APP_USER: arun
  APP_PORT: 80

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    
    steps:
      - name: Running single command in JOB1
        run: echo "Hi this is Hemant's workdlow"
      - name: check1
        run: |
          pwd
          ls -al
          hostname
      - name: Step 2 Checkout
        uses: actions/checkout@v6.1.0 #git market place

      - name: Step 3 Check
        run: |
          mkdir archive1
          pwd
          ls -al
          hostname
          echo "this is the artifact" >> myfact.txt
          echo "This is an aftifact file to be tested" >> archive1/mai1l.txt
          echo "This will be the 3rd file to be tested in this manner" >> archive1/mai1n.txt
          echo "this is test" >> by.txt

      - name: upload single_file
        uses: actions/upload-artifact@v7  # git market place
        with:
          name: single_path
          path: |
            ./by.txt

         
  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking the current directory
        run: |
          pwd
          ls -al

      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0 #git market place
        with:
          name: single_path
      - name: checking current directory post download
        run: |
          pwd
          ls -al

      - name: Refering the environment variable 
        run: |
         echo "[INFO] We are currently on envidonment - $ENV_TYPE and logged in with user $APP_USER"
         echo "[INFO] The application is running on port $APP_PORT"    
      
      - name: Refring to the sectets 
        run: echo "[INFO] We refer to the secret in this case by - ${{ secrets.APP_PASSWD_DEMO }}"

  job3:
     name: JOB3
     needs: [job1, job2]
     runs-on: ubuntu-latest
     steps:
       - name: Running github defined variables 
         run: |
           echo "[INFO] This is to test which repo we are in : ${{ github.event_name }} "
           echo "[INFO] This is for changes added by : ${{ github.actor }} and in ${{ github.ref_name }} branch "
           echo "[INFO] This is for the current step is running on : ${{ runner.os }}"
           echo "[INFO] To check the current run ID : ${{ JOB.check_run_id }}"

  staging:
    name: Staging_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Staging Deployment test 
        run: echo "[INFO] The staging portal is ${{ vars.HOST }} and the user is ${{ vars.USER }}"
      - name: Refering staging environment Secret    
        run: echo "[INFO] The password for  ${{ vars.USER }} is ${{ secrets.PASSWORD }}"
    environment:
      name: Staging
    if: github.ref == 'refs/heads/dev'

  production:
    name: Production_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Production Deployment test 
        run: echo "[INFO] The staging portal is  ${{ vars.HOST }} and the user is  ${{ vars.USER }}"
      - name: Refering production environment Secret    
        run: echo "[INFO] The password for  ${{ vars.USER }} is ${{ secrets.PASSWORD }}"
    environment:
      name: Production
    if: github.ref == 'refs/heads/main'
