name: Second-file
on: 
  schedule:
    - cron: "*/ * * * *"

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: This is to test the working 
        run: echo "this is the test module"
      - name: This is the working user 
        run: hostname
      - name: This is the timer
        run: sleep 10
  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: This is the test
        run: df -h
      - name: Test
        run: free -h
      - name: This is the timer
        run: sleep 5

  job3:
    name: JOB3
    needs: [job2, job1]
    runs-on: ubuntu-latest
    steps:
      - name: This is to test the 3rd release
        run: pwd
      - name: This is the timer
        run: sleep 7

  job4:
    name: JOB4
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: FINAL CASE
        run: uptime
      - name: this case check
        run: ps -aef|grep 0
      
